# Generated by Django 6.0.7 on 2026-07-12 10:33

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=10)),
                ('license_expiry', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('safety_score', models.PositiveSmallIntegerField(default=100)),
                ('status', django_fsm.FSMField(default='Available', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
