# Generated by Django 6.0.4 on 2026-07-12 11:12

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', django_fsm.FSMField(default='Available', max_length=50, protected=True)),
                ('maintenance_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
