# Generated by Django 6.0.7 on 2026-07-12 12:23

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=django_fsm.FSMField(default='Available', max_length=50, protected=True),
        ),
    ]
