# Generated by Django 6.0.7 on 2026-07-12 12:09

import django.db.models.deletion
import documents.models
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('license', 'Driver License'), ('insurance', 'Vehicle Insurance'), ('registration', 'Vehicle Registration')], max_length=20)),
                ('file', models.FileField(upload_to=documents.models.compliance_document_upload_path, validators=[documents.validators.validate_file_extension, documents.validators.validate_file_size])),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['expiry_date', 'title'],
            },
        ),
    ]
