# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('maintenance', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='odometer_at_service',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
