# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('maintenance', '0002_alter_maintenancelog_status'),
        ('maintenance', '0002_maintenancelog_odometer_at_service'),
    ]

    operations = []
