# Generated by Django 6.0.4 on 2026-07-12 11:28

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('planned_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', django_fsm.FSMField(default='Draft', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
        ),
    ]
